# Generated by Django 3.1.8 on 2021-04-29 14:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_newscategory_newstagindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="news.NewsCategory"
            ),
        ),
    ]
